"""add_retailer_to_staging

Revision ID: fcd7eb91e9b6
Revises: d78cb5129604
Create Date: 2025-06-16 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd7eb91e9b6'
down_revision = 'd78cb5129604'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staging_raw_offers', sa.Column('retailer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staging_raw_offers', 'retailer')
    # ### end Alembic commands ### 